user bits_backend
topic read cas/+/status
topic read cas/+/telemetry/#
topic read cas/+/commands/ack
topic read cas/+/run/#
topic write cas/+/run/ack
topic write cas/+/commands
topic read bits/v1/ops/req/#
topic write bits/v1/ops/res/#
topic write bits/v1/ops/state/#
topic write bits/v1/ops/evt/#

user bits_admin
topic read cas/#
topic read bits/#
topic read $SYS/#

user dev_{sender}
topic write cas/{sender}/status
topic write cas/{sender}/telemetry/#
topic write cas/{sender}/weight/#
topic write cas/{sender}/commands/ack
topic read cas/{sender}/commands

user dev_{relay}
topic write cas/{relay}/status
topic write cas/{relay}/telemetry/#
topic write cas/{relay}/commands/ack
topic write cas/{relay}/run/#
topic read cas/{relay}/commands
topic read cas/{relay}/run/ack
topic read cas/{sender}/weight/ctl

user app_{station}
topic write bits/v1/ops/req/app_{station}/#
topic read bits/v1/ops/res/app_{station}/#
topic read bits/v1/ops/state/#
topic read bits/v1/ops/evt/#
