listener 1883
protocol mqtt
allow_anonymous false
password_file /etc/mosquitto/bits/passwd
acl_file /etc/mosquitto/bits/acl.conf
use_username_as_clientid true
max_packet_size 65536
max_inflight_messages 20
max_queued_messages 1000
persistence true
persistence_location /var/lib/mosquitto/
autosave_interval 30
sys_interval 10
log_dest file /var/log/mosquitto/bits.log
log_type error
log_type warning
log_type notice
connection_messages true
